language: generic
sudo: required

env:
  - IMAGE_NAME="golang:staging"
    GO_VERSION="1.12.6"

services:
  - docker

before_install:
  - docker build -t jpskgc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jpskgc/react-test npm test
  - curl -o structure-test -sSLO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
  - chmod +x structure-test
  - docker build -t "go1-builder:${GO_VERSION}" --build-arg go_version="${GO_VERSION}" -q runtime-builder/
  - ./structure-test test --image "go1-builder:${GO_VERSION}" --config runtime-builder/tests/structure/test_config.yaml

after_success:
  - docker build -t jpskgc/multi-client ./client
  - docker build -t jpskgc/multi-nginx ./nginx
  - docker build -t jpskgc/multi-api ./api
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jpskgc/multi-client
  - docker push jpskgc/multi-nginx
  - docker push jpskgc/multi-api
deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-340135579499
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
