version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
  aws-ecs: circleci/aws-ecs@0.0.8

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'article-ecr-jpskgc'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'article-task-jpskgc'
          cluster-name: 'article-cluster-jpskgc'
          service-name: 'article-service-jpskgc'
          container-image-name-updates: 'container=article-container-jpskgc,tag=${CIRCLE_SHA1}'
